"""empty message

Revision ID: 5adb2a754bfd
Revises: 5e3cd395f772
Create Date: 2021-04-08 11:56:04.009805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5adb2a754bfd'
down_revision = '5e3cd395f772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchase_discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Сoupon')
    # ### end Alembic commands ###
