"""empty message

Revision ID: 6ea158effa31
Revises: 5adb2a754bfd
Create Date: 2021-04-08 16:31:25.286928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ea158effa31'
down_revision = '5adb2a754bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('сoupon')
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=20), nullable=True),
    sa.Column('coupon_discount', sa.Integer(), nullable=True),
    sa.Column('coupon_is_added', sa.Boolean(), nullable=True),
    sa.Column('coupon_is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
