"""empty message

Revision ID: 8950418448d9
Revises: 2f94592faa3d
Create Date: 2021-04-08 11:43:44.056518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8950418448d9'
down_revision = '2f94592faa3d'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column('purchase', 'purchase_discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchase_discount', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
