"""empty message

Revision ID: 89ff515cabd4
Revises: 6ea158effa31
Create Date: 2021-04-30 12:02:53.122801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ff515cabd4'
down_revision = '6ea158effa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_author', sa.String(length=100), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_publish_date', sa.DateTime(), nullable=True),
    sa.Column('comment_clothes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_clothes_id'], ['clothes_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
