"""empty message

Revision ID: fe64ee94f4ef
Revises: 8950418448d9
Create Date: 2021-04-08 11:46:33.602081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe64ee94f4ef'
down_revision = '8950418448d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchase_discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'purchase_discount')
    # ### end Alembic commands ###
